#!/usr/bin/env node
/**
 * generateManifest.js
 *
 * Run this from the project root to auto-generate src/audioManifest.js
 * by scanning all files in src/assests/<folder>/.
 *
 * Usage:
 *   node generateManifest.js
 *
 * This regenerates src/audioManifest.js — commit the result.
 * You never need to hand-edit audioManifest.js again; just re-run this
 * script whenever you add new audio files.
 */

const fs   = require("fs");
const path = require("path");

const ASSETS_DIR  = path.join(__dirname, "src", "assests");
const OUTPUT_FILE = path.join(__dirname, "src", "audioManifest.js");

// Audio + image extensions to include
const VALID_EXTS = new Set([".mp3", ".wav", ".ogg", ".flac", ".aac", ".m4a", ".opus", ".webm", ".png", ".jpg", ".jpeg", ".gif", ".webp"]);

// Read all theme folders
const folders = fs.readdirSync(ASSETS_DIR).filter(name => {
  return fs.statSync(path.join(ASSETS_DIR, name)).isDirectory();
});

// For each folder, read all valid files
const themes = {};
const importLines = [];
let varIdx = 0;

folders.forEach(folder => {
  const folderPath = path.join(ASSETS_DIR, folder);
  const files = fs.readdirSync(folderPath).filter(f => {
    const ext = path.extname(f).toLowerCase();
    return VALID_EXTS.has(ext) && !f.startsWith(".");
  }).sort();

  if (!files.length) return;

  // Derive a clean theme name from the folder name
  // e.g. "acAssets" → "Animal Crossing" (we keep original folder name as key
  // so users can rename in the app)
  const themeName = folder; // users can rename themes in the app

  themes[themeName] = files.map(filename => {
    const varName = `asset_${varIdx++}`;
    const relPath = `./assests/${folder}/${filename}`;
    importLines.push(`import ${varName} from "${relPath}";`);
    return { name: filename, varName };
  });
});

// Build the JS output
const lines = [];

lines.push("/**");
lines.push(" * audioManifest.js — AUTO-GENERATED by generateManifest.js");
lines.push(" * Do not edit manually. Run: node generateManifest.js");
lines.push(" */");
lines.push("");
lines.push("/* eslint-disable */");
lines.push("");

// All imports
importLines.forEach(l => lines.push(l));
lines.push("");

// ASSET_THEMES object
lines.push("export const ASSET_THEMES = {");
Object.entries(themes).forEach(([folder, files], i, arr) => {
  lines.push(`  ${JSON.stringify(folder)}: [`);
  files.forEach(({name, varName}) => {
    lines.push(`    { name: ${JSON.stringify(name)}, url: ${varName} },`);
  });
  lines.push(`  ]${i < arr.length - 1 ? "," : ""}`);
});
lines.push("};");
lines.push("");

// Helper functions
lines.push(`export function getManifestFileMap(themeName) {`);
lines.push(`  const files = ASSET_THEMES[themeName] || [];`);
lines.push(`  const map = {};`);
lines.push(`  files.forEach(f => { map[f.name] = f.url; });`);
lines.push(`  return map;`);
lines.push(`}`);
lines.push("");
lines.push(`export function getManifestFiles(themeName) {`);
lines.push(`  return ASSET_THEMES[themeName] || [];`);
lines.push(`}`);
lines.push("");
lines.push(`export function getManifestThemeNames() {`);
lines.push(`  return Object.keys(ASSET_THEMES);`);
lines.push(`}`);
lines.push("");

const output = lines.join("\n");
fs.writeFileSync(OUTPUT_FILE, output, "utf8");

console.log(`✅ Generated ${OUTPUT_FILE}`);
console.log(`   ${Object.keys(themes).length} theme folders:`);
Object.entries(themes).forEach(([folder, files]) => {
  console.log(`   • ${folder}: ${files.length} files`);
});
