import { useState, useRef } from "react";
import { ASSET_THEMES } from "../audioManifest";

const LS = { get:(k,fb)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):fb;}catch{return fb;}}, set:(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));}catch{}} };

/**
 * Generates and downloads a fresh audioManifest.js based on the currently
 * bundled ASSET_THEMES. The downloaded file is a drop-in replacement for
 * src/audioManifest.js — but note: to add NEW files you still need to run
 * generateManifest.js locally (since imports must be resolved at build time).
 * This button is useful for regenerating the helper functions / structure.
 */
function downloadGeneratedManifest() {
  const themeNames = Object.keys(ASSET_THEMES);
  const lines = [];

  lines.push("/**");
  lines.push(" * audioManifest.js — generated by the app on " + new Date().toISOString());
  lines.push(" *");
  lines.push(" * NOTE: This file contains the STRUCTURE only — not the actual import statements.");
  lines.push(" * To add NEW audio files, run: node generateManifest.js from your project root.");
  lines.push(" * That script scans src/assests/ and rebuilds this file with correct imports.");
  lines.push(" */");
  lines.push("");
  lines.push("/* eslint-disable */");
  lines.push("");
  lines.push("// ── Re-run 'node generateManifest.js' to regenerate with new files ──");
  lines.push("// The imports below need to be resolved at build time by webpack.");
  lines.push("// This exported structure shows what the current build contains.");
  lines.push("");
  lines.push("export const ASSET_THEMES = {");
  themeNames.forEach((name, i) => {
    const files = ASSET_THEMES[name] || [];
    lines.push(`  ${JSON.stringify(name)}: [`);
    files.forEach(f => {
      lines.push(`    { name: ${JSON.stringify(f.name)}, url: ${JSON.stringify(f.url)} },`);
    });
    lines.push(`  ]${i < themeNames.length - 1 ? "," : ""}`);
  });
  lines.push("};");
  lines.push("");
  lines.push("export function getManifestFileMap(themeName) {");
  lines.push("  const files = ASSET_THEMES[themeName] || [];");
  lines.push("  const map = {};");
  lines.push("  files.forEach(f => { map[f.name] = f.url; });");
  lines.push("  return map;");
  lines.push("}");
  lines.push("");
  lines.push("export function getManifestFiles(themeName) {");
  lines.push("  return ASSET_THEMES[themeName] || [];");
  lines.push("}");
  lines.push("");
  lines.push("export function getManifestThemeNames() {");
  lines.push("  return Object.keys(ASSET_THEMES);");
  lines.push("}");
  lines.push("");

  const blob = new Blob([lines.join("\n")], { type: "text/javascript" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = "audioManifest.js";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}



export const FONT_OPTIONS = [
  { label:"Monospace",       value:"monospace",                      preview:"00:00" },
  { label:"Helvetica",       value:"Helvetica, Arial, sans-serif",   preview:"00:00" },
  { label:"Georgia",         value:"Georgia, serif",                 preview:"00:00" },
  { label:"Courier New",     value:"'Courier New', monospace",       preview:"00:00" },
  { label:"Verdana",         value:"Verdana, sans-serif",            preview:"00:00" },
  { label:"Trebuchet MS",    value:"'Trebuchet MS', sans-serif",     preview:"00:00" },
  { label:"Inter",           value:"'Inter', sans-serif",            google:"Inter" },
  { label:"Roboto Mono",     value:"'Roboto Mono', monospace",       google:"Roboto+Mono" },
  { label:"Space Grotesk",   value:"'Space Grotesk', sans-serif",    google:"Space+Grotesk" },
  { label:"DM Sans",         value:"'DM Sans', sans-serif",          google:"DM+Sans" },
  { label:"Outfit",          value:"'Outfit', sans-serif",           google:"Outfit" },
  { label:"Syne",            value:"'Syne', sans-serif",             google:"Syne" },
  { label:"Oxanium",         value:"'Oxanium', sans-serif",          google:"Oxanium" },
];

const COLOR_FIELDS = [
  ["pomodoroColor",   "Pomodoro background"],
  ["shortBreakColor", "Short Break background"],
  ["longBreakColor",  "Long Break background"],
  ["textColor",       "Phase button text"],
  ["bgColor",         "App background"],
  ["timerTextColor",  "Timer digits"],
];

function pad2(n) { return String(Math.max(0,parseInt(n,10)||0)).padStart(2,"0"); }

function parseTimeStr(t){
  if(typeof t==="string"&&t.includes(":")){ const[m,s]=t.split(":").map(Number);return{mins:m||0,secs:s||0}; }
  return{mins:parseInt(t,10)||0,secs:0};
}
function toTimeStr(mins,secs){ return `${pad2(mins)}:${pad2(secs)}`; }

// ── Export helpers ────────────────────────────────────────────────────────
// Strip audio dataURLs from clips — keep only the filename for re-linking later
function stripAudio(themes) {
  function stripClip(c) { const out={...c}; delete out.url; return out; }
  function stripTheme(t) {
    const sm = {};
    for (const [k,v] of Object.entries(t.stageMap||{})) {
      sm[k] = {...v, clips:(v.clips||[]).map(stripClip)};
    }
    return {...t, stageMap:sm, wildcardClips:(t.wildcardClips||[]).map(stripClip), subThemes:(t.subThemes||[]).map(stripTheme)};
  }
  return themes.map(stripTheme);
}

// Re-link: walk themes and fill in .url for any clip whose .name matches an uploaded file
function relinkThemes(themes, fileMap) {
  function relinkClip(c) {
    const url = fileMap[c.name] || fileMap[c.name.toLowerCase()];
    return url ? {...c, url} : c;
  }
  function relinkTheme(t) {
    const sm = {};
    for (const [k,v] of Object.entries(t.stageMap||{})) {
      sm[k] = {...v, clips: (v.clips||[]).map(relinkClip)};
    }
    return {
      ...t,
      stageMap: sm,
      wildcardClips: (t.wildcardClips||[]).map(relinkClip),
      subThemes: (t.subThemes||[]).map(relinkTheme),
    };
  }
  return themes.map(relinkTheme);
}

// Count how many clips successfully got a URL after relinking
function countLinked(themes) {
  let linked=0, total=0;
  function walk(t) {
    for (const v of Object.values(t.stageMap||{})) {
      for (const c of (v.clips||[])) { total++; if(c.url)linked++; }
    }
    for (const c of (t.wildcardClips||[])) { total++; if(c.url)linked++; }
    for (const s of (t.subThemes||[])) walk(s);
  }
  themes.forEach(walk);
  return {linked, total};
}

export default function Settings({
  pTime,sTime,lTime,setPTime,setSTime,setLTime,
  interval,setInterval,
  showSeconds,setShowSeconds,
  autoStartBreaks,setAutoStartBreaks,
  autoStartPomodoros,setAutoStartPomodoros,
  colors,setColors,
  font,setFont,
}) {
  const [open, setOpen] = useState(false);
  const [tab,  setTab]  = useState("timer");

  const pP=parseTimeStr(pTime),sP=parseTimeStr(sTime),lP=parseTimeStr(lTime);
  const [draft, setDraft] = useState({pMins:pP.mins,pSecs:pP.secs,sMins:sP.mins,sSecs:sP.secs,lMins:lP.mins,lSecs:lP.secs,interval});
  const [draftColors, setDraftColors] = useState(colors);
  const [draftFont,   setDraftFont]   = useState(font);
  const [customFonts, setCustomFonts] = useState(()=>LS.get("pomo_customFonts",[]));

  // Export/import state
  const [relinkStatus, setRelinkStatus] = useState(null); // null | {linked,total,missing:[]}
  const [importMsg,    setImportMsg]    = useState(null); // success/error string

  const fontFileRef   = useRef(null);
  const importFileRef = useRef(null);
  const relinkFileRef = useRef(null);

  function openPanel(){
    const pp=parseTimeStr(pTime),sp=parseTimeStr(sTime),lp=parseTimeStr(lTime);
    setDraft({pMins:pp.mins,pSecs:pp.secs,sMins:sp.mins,sSecs:sp.secs,lMins:lp.mins,lSecs:lp.secs,interval});
    setDraftColors({...colors});
    setDraftFont(font);
    setRelinkStatus(null);
    setImportMsg(null);
    setOpen(true);
  }

  async function handleFontUpload(e){
    const f=e.target.files[0]; if(!f)return;
    const name=f.name.replace(/\.[^.]+$/,"");
    const dataUrl=await new Promise(res=>{const r=new FileReader();r.onload=ev=>res(ev.target.result);r.readAsDataURL(f);});
    const fontName=`CustomFont_${Date.now()}`;
    const style=document.createElement("style");
    style.textContent=`@font-face{font-family:'${fontName}';src:url('${dataUrl}');}`;
    document.head.appendChild(style);
    const entry={label:`Custom: ${name}`,value:`'${fontName}',monospace`,dataUrl};
    const next=[...customFonts,entry];
    setCustomFonts(next);
    LS.set("pomo_customFonts",next);
    setDraftFont(entry.value);
    e.target.value="";
  }

  // ── Generate audioManifest.js ──────────────────────────────────────────
  // Produces a fresh audioManifest.js from the current ASSET_THEMES bundle.
  // Download it and replace src/audioManifest.js in your repo, then redeploy.


  // ── Export ────────────────────────────────────────────────────────────────
  function handleExport() {
    const themes = LS.get("pomo_themes_v3", []);
    const payload = {
      version: 1,
      exportedAt: new Date().toISOString(),
      settings: {
        pTime, sTime, lTime, interval,
        showSeconds, autoStartBreaks, autoStartPomodoros,
        colors, font,
      },
      themes: stripAudio(themes),
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], {type:"application/json"});
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = `pomodoro-config-${new Date().toISOString().slice(0,10)}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 10000);
  }

  // ── Import ────────────────────────────────────────────────────────────────
  function handleImport(e) {
    const file = e.target.files[0];
    if (!file) return;

    if (!file.name.endsWith(".json")) {
      setImportMsg("❌ Wrong file type — please select a .json file exported from this app.");
      e.target.value = "";
      return;
    }

    const reader = new FileReader();
    reader.onload = ev => {
      let payload;
      try {
        payload = JSON.parse(ev.target.result);
      } catch {
        setImportMsg("❌ Could not read the file — it doesn't appear to be valid JSON. Make sure you're selecting the exported .json file and that it hasn't been edited manually.");
        return;
      }

      if (!payload.version) {
        setImportMsg("❌ This file isn't a Pomodoro config export — the 'version' field is missing. Make sure you're using a file exported by this app.");
        return;
      }
      if (!Array.isArray(payload.themes)) {
        setImportMsg("❌ The file is missing the themes list. It may be corrupted or from an incompatible version.");
        return;
      }

      try {
        const s = payload.settings || {};
        if (s.pTime)    { LS.set("pomo_pTime",    s.pTime);    setPTime(s.pTime); }
        if (s.sTime)    { LS.set("pomo_sTime",    s.sTime);    setSTime(s.sTime); }
        if (s.lTime)    { LS.set("pomo_lTime",    s.lTime);    setLTime(s.lTime); }
        if (s.interval) { LS.set("pomo_interval", s.interval); setInterval(s.interval); }
        if (s.colors)   { LS.set("pomo_colors",   s.colors);   setColors(s.colors); }
        if (s.font)     { LS.set("pomo_font",     s.font);     setFont(s.font); }
        if (s.showSeconds        !== undefined) { LS.set("pomo_showSec",   s.showSeconds);        setShowSeconds(s.showSeconds); }
        if (s.autoStartBreaks    !== undefined) { LS.set("pomo_autoBreak", s.autoStartBreaks);    setAutoStartBreaks(s.autoStartBreaks); }
        if (s.autoStartPomodoros !== undefined) { LS.set("pomo_autoPomo",  s.autoStartPomodoros); setAutoStartPomodoros(s.autoStartPomodoros); }
      } catch(err) {
        setImportMsg(`❌ Settings could not be fully restored: ${err.message}`);
        return;
      }

      try {
        LS.set("pomo_themes_v3", payload.themes);
      } catch(err) {
        setImportMsg(`❌ Themes could not be saved to local storage: ${err.message}. Try clearing browser data and retrying.`);
        return;
      }

      const themeCount = payload.themes.length;
      const subCount = payload.themes.reduce((n,t)=>(t.subThemes||[]).length+n, 0);
      setImportMsg(
        `✅ Imported ${themeCount} theme${themeCount!==1?"s":""}` +
        (subCount ? ` (+ ${subCount} sub-theme${subCount!==1?"s":""})` : "") +
        `. Reload the page to see your themes.`
      );
      setRelinkStatus(null);
      // Auto-reload after 1.5s so themes appear — localStorage is written, just need a fresh mount
      setTimeout(() => window.location.reload(), 1500);
    };
    reader.onerror = () => {
      setImportMsg("❌ Failed to read the file. Check that it isn't corrupted and try again.");
    };
    reader.readAsText(file);
    e.target.value = "";
  }

  // ── Re-link audio from folder ─────────────────────────────────────────────
  async function handleRelink(e) {
    const files = Array.from(e.target.files || []);
    if (!files.length) return;

    // Build filename → dataURL map
    const fileMap = {};
    await Promise.all(files.map(f => new Promise(res => {
      const reader = new FileReader();
      reader.onload = ev => { fileMap[f.name] = ev.target.result; res(); };
      reader.readAsDataURL(f);
    })));

    const themes = LS.get("pomo_themes_v3", []);
    const relinked = relinkThemes(themes, fileMap);
    LS.set("pomo_themes_v3", relinked);

    const {linked, total} = countLinked(relinked);
    // Find which clips are still missing
    const missing = [];
    function findMissing(t) {
      for (const v of Object.values(t.stageMap||{}))
        for (const c of (v.clips||[])) if(!c.url) missing.push(c.name);
      for (const c of (t.wildcardClips||[])) if(!c.url) missing.push(c.name);
      for (const s of (t.subThemes||[])) findMissing(s);
    }
    relinked.forEach(findMissing);

    setRelinkStatus({linked, total, missing: [...new Set(missing)]});
    e.target.value = "";
  }

  function applyAll(){
    const newP=toTimeStr(draft.pMins,draft.pSecs);
    const newS=toTimeStr(draft.sMins,draft.sSecs);
    const newL=toTimeStr(draft.lMins,draft.lSecs);
    const newI=Math.max(1,parseInt(draft.interval,10)||1);

    const chosen=[...FONT_OPTIONS,...customFonts].find(f=>f.value===draftFont);
    if(chosen?.google){
      const id=`gf-${chosen.google}`;
      if(!document.getElementById(id)){
        const link=document.createElement("link");
        link.id=id;link.rel="stylesheet";
        link.href=`https://fonts.googleapis.com/css2?family=${chosen.google}:wght@400;700;900&display=swap`;
        document.head.appendChild(link);
      }
    }
    customFonts.forEach(cf=>{
      const cfName=cf.value.replace(/['"]/g,"").split(",")[0];
      if(!document.querySelector(`style[data-font="${cfName}"]`)){
        const s=document.createElement("style");
        s.setAttribute("data-font",cfName);
        s.textContent=`@font-face{font-family:'${cfName}';src:url('${cf.dataUrl}');}`;
        document.head.appendChild(s);
      }
    });

    setPTime(newP);setSTime(newS);setLTime(newL);
    setInterval(newI);
    setColors(draftColors);
    setFont(draftFont);
    setOpen(false);
  }

  const d=(k,v)=>setDraft(p=>({...p,[k]:Math.max(0,parseInt(v,10)||0)}));
  const C2={bg:"#0f0e1a",border:"#1e1d2e",text:"#e0ddf5",muted:"#555",accent:"#7c6af7",card:"#13121f"};
  const inp2={background:C2.card,border:`1px solid ${C2.border}`,borderRadius:8,padding:"7px 10px",color:C2.text,fontSize:13,outline:"none",boxSizing:"border-box"};
  const numInp={...inp2,width:58,textAlign:"center",fontFamily:"monospace",fontWeight:700};
  const tBtn=(active)=>({padding:"5px 12px",borderRadius:"7px 7px 0 0",cursor:"pointer",background:active?C2.card:"transparent",border:active?`1px solid ${C2.border}`:"1px solid transparent",borderBottom:active?`1px solid ${C2.bg}`:`1px solid ${C2.border}`,color:active?C2.text:C2.muted,fontSize:12});
  const actionBtn=(col)=>({display:"inline-flex",alignItems:"center",gap:6,padding:"9px 16px",borderRadius:9,border:`1px solid ${col}`,color:col,background:"transparent",fontSize:13,fontWeight:700,cursor:"pointer",width:"100%",justifyContent:"center"});

  const allFonts=[...FONT_OPTIONS,...customFonts];

  return (
    <>
      <button onClick={openPanel} style={{ padding:"8px 14px",margin:4,borderRadius:8,background:"transparent",border:"1px solid rgba(255,255,255,.25)",color:"#fff",fontWeight:700,fontSize:13,cursor:"pointer",alignSelf:"flex-start",marginTop:12 }}>
        ⚙ Settings
      </button>

      {open&&(
        <div style={{ position:"fixed",inset:0,background:"rgba(0,0,0,.85)",zIndex:500,display:"flex",alignItems:"center",justifyContent:"center" }}
          onClick={e=>e.target===e.currentTarget&&setOpen(false)}>
          <div style={{ background:C2.bg,border:`1px solid ${C2.border}`,borderRadius:16,width:"min(500px,96vw)",maxHeight:"88vh",display:"flex",flexDirection:"column",boxShadow:"0 32px 100px rgba(0,0,0,.9)",fontFamily:"'Segoe UI',system-ui,sans-serif" }}>

            <div style={{ display:"flex",alignItems:"center",justifyContent:"space-between",padding:"16px 20px",borderBottom:`1px solid ${C2.border}` }}>
              <span style={{ fontSize:16,fontWeight:800,color:C2.text }}>Settings</span>
              <button onClick={()=>setOpen(false)} style={{ background:"none",border:"none",color:C2.muted,fontSize:20,cursor:"pointer" }}>✕</button>
            </div>

            <div style={{ display:"flex",padding:"10px 20px 0",gap:4,borderBottom:`1px solid ${C2.border}`,flexWrap:"wrap" }}>
              {[["timer","⏱ Timer"],["appearance","🎨 Colors"],["font","🔤 Font"],["backup","💾 Backup"]].map(([k,l])=>(
                <button key={k} onClick={()=>setTab(k)} style={tBtn(tab===k)}>{l}</button>
              ))}
            </div>

            <div style={{ overflowY:"auto",padding:"18px 20px",flex:1 }}>

              {/* ── Timer ── */}
              {tab==="timer"&&<>
                <p style={{ fontSize:11,fontWeight:700,color:C2.muted,textTransform:"uppercase",letterSpacing:.8,marginBottom:12 }}>Duration (MM : SS)</p>
                {[["Pomodoro","pMins","pSecs"],["Short Break","sMins","sSecs"],["Long Break","lMins","lSecs"]].map(([label,mk,sk])=>(
                  <div key={mk} style={{ display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:14 }}>
                    <label style={{ fontSize:13,color:C2.text }}>{label}</label>
                    <div style={{ display:"flex",alignItems:"center",gap:6 }}>
                      <input type="number" min="0" max="99" style={numInp}
                        value={pad2(draft[mk])}
                        onChange={e=>d(mk,e.target.value)}/>
                      <span style={{ color:C2.muted,fontSize:18,fontWeight:700 }}>:</span>
                      <input type="number" min="0" max="59" style={numInp}
                        value={pad2(draft[sk])}
                        onChange={e=>d(sk,Math.min(59,parseInt(e.target.value,10)||0))}/>
                    </div>
                  </div>
                ))}
                <div style={{ display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:20 }}>
                  <label style={{ fontSize:13,color:C2.text }}>Pomodoros per cycle</label>
                  <input type="number" min="1" max="12" style={numInp} value={pad2(draft.interval)} onChange={e=>d("interval",e.target.value)}/>
                </div>

                <hr style={{ border:"none",borderTop:`1px solid ${C2.border}`,margin:"16px 0" }}/>
                <p style={{ fontSize:11,fontWeight:700,color:C2.muted,textTransform:"uppercase",letterSpacing:.8,marginBottom:12 }}>Display &amp; Auto-start</p>
                {[
                  ["Show seconds on timer",            showSeconds,        setShowSeconds],
                  ["Auto-start break after pomodoro",  autoStartBreaks,    setAutoStartBreaks],
                  ["Auto-start pomodoro after break",  autoStartPomodoros, setAutoStartPomodoros],
                ].map(([label,val,setter])=>(
                  <div key={label} style={{ display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:12 }}>
                    <span style={{ fontSize:13,color:C2.text }}>{label}</span>
                    <div onClick={()=>setter(p=>!p)} style={{ width:34,height:18,borderRadius:9,position:"relative",background:val?"#7c6af7":"#222",cursor:"pointer",transition:"background .2s" }}>
                      <div style={{ width:14,height:14,borderRadius:"50%",background:"#fff",position:"absolute",top:2,left:val?18:2,transition:"left .2s" }}/>
                    </div>
                  </div>
                ))}
              </>}

              {/* ── Colors ── */}
              {tab==="appearance"&&<>
                <p style={{ fontSize:11,fontWeight:700,color:C2.muted,textTransform:"uppercase",letterSpacing:.8,marginBottom:14 }}>UI Colors</p>
                {COLOR_FIELDS.map(([key,label])=>(
                  <div key={key} style={{ display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:14 }}>
                    <span style={{ fontSize:13,color:C2.text }}>{label}</span>
                    <div style={{ display:"flex",alignItems:"center",gap:8 }}>
                      <div style={{ width:28,height:28,borderRadius:7,background:draftColors[key],border:`1px solid ${C2.border}` }}/>
                      <input type="color" value={draftColors[key]} onChange={e=>setDraftColors(p=>({...p,[key]:e.target.value}))}
                        style={{ width:36,height:28,borderRadius:7,border:`1px solid ${C2.border}`,background:"transparent",cursor:"pointer",padding:0 }}/>
                      <span style={{ fontSize:11,color:"#444",fontFamily:"monospace",width:70 }}>{draftColors[key]}</span>
                    </div>
                  </div>
                ))}
                <button onClick={()=>setDraftColors({pomodoroColor:"#f87171",shortBreakColor:"#34d399",longBreakColor:"#22d3ee",textColor:"#ffffff",bgColor:"#000000",timerTextColor:"#ffffff"})}
                  style={{ fontSize:11,color:C2.muted,background:"none",border:"none",cursor:"pointer",textDecoration:"underline",marginTop:4 }}>Reset to defaults</button>
              </>}

              {/* ── Font ── */}
              {tab==="font"&&<>
                <p style={{ fontSize:11,fontWeight:700,color:C2.muted,textTransform:"uppercase",letterSpacing:.8,marginBottom:14 }}>Timer Font</p>
                <div style={{ background:C2.card,borderRadius:10,padding:"12px 14px",border:`1px solid ${C2.border}`,marginBottom:16 }}>
                  <div style={{ fontSize:12,fontWeight:700,color:C2.text,marginBottom:6 }}>Upload custom font</div>
                  <p style={{ fontSize:11,color:C2.muted,marginBottom:8 }}>Upload any .ttf, .otf, or .woff2 file.</p>
                  <label style={{ display:"inline-flex",alignItems:"center",gap:6,padding:"6px 12px",borderRadius:8,border:`1px solid ${C2.accent}`,color:C2.accent,fontSize:12,cursor:"pointer" }}>
                    📂 Choose font file
                    <input ref={fontFileRef} type="file" accept=".ttf,.otf,.woff,.woff2" style={{ display:"none" }} onChange={handleFontUpload}/>
                  </label>
                </div>
                <div style={{ display:"flex",flexDirection:"column",gap:6 }}>
                  {allFonts.map(f=>(
                    <div key={f.value} onClick={()=>setDraftFont(f.value)}
                      style={{ display:"flex",alignItems:"center",justifyContent:"space-between",padding:"10px 14px",borderRadius:10,cursor:"pointer",border:`1px solid ${draftFont===f.value?C2.accent:C2.border}`,background:draftFont===f.value?`${C2.accent}18`:C2.card,transition:"border-color .15s" }}>
                      <span style={{ fontSize:13,color:C2.text }}>{f.label}</span>
                      <span style={{ fontSize:22,fontFamily:f.value,fontWeight:700,color:draftFont===f.value?C2.accent:C2.muted }}>00:00</span>
                    </div>
                  ))}
                </div>
              </>}

              {/* ── Backup ── */}
              {tab==="backup"&&<>
                <p style={{ fontSize:11,fontWeight:700,color:C2.muted,textTransform:"uppercase",letterSpacing:.8,marginBottom:4 }}>Export</p>
                <p style={{ fontSize:12,color:C2.muted,marginBottom:12,lineHeight:1.6 }}>
                  Saves all your themes, stage assignments, and settings to a <code style={{color:C2.accent}}>.json</code> file.
                  Audio clips are referenced by <strong style={{color:C2.text}}>filename only</strong> — not embedded.
                  Keep your audio folder on Google Drive to re-link on any device.
                </p>
                <button onClick={handleExport} style={actionBtn("#22c55e")}>
                  ⬇ Export config to file
                </button>

                <hr style={{ border:"none",borderTop:`1px solid ${C2.border}`,margin:"20px 0" }}/>

                <p style={{ fontSize:11,fontWeight:700,color:C2.muted,textTransform:"uppercase",letterSpacing:.8,marginBottom:4 }}>Import</p>
                <p style={{ fontSize:12,color:C2.muted,marginBottom:12,lineHeight:1.6 }}>
                  Load a previously exported <code style={{color:C2.accent}}>.json</code> config file.
                  Settings and theme structure are restored immediately.
                  Then use <strong style={{color:C2.text}}>Re-link audio</strong> below to restore your sounds.
                </p>
                <label style={actionBtn("#3b82f6")}>
                  ⬆ Import config from file
                  <input ref={importFileRef} type="file" accept=".json" style={{display:"none"}} onChange={handleImport}/>
                </label>

                {importMsg&&(
                  <div style={{ marginTop:10,padding:"10px 14px",borderRadius:9,background:`${importMsg.startsWith("✅")?"#22c55e":"#ef4444"}18`,border:`1px solid ${importMsg.startsWith("✅")?"#22c55e":"#ef4444"}44`,fontSize:12,color:C2.text,lineHeight:1.6 }}>
                    {importMsg}
                  </div>
                )}

                <hr style={{ border:"none",borderTop:`1px solid ${C2.border}`,margin:"20px 0" }}/>

                <p style={{ fontSize:11,fontWeight:700,color:C2.muted,textTransform:"uppercase",letterSpacing:.8,marginBottom:4 }}>Re-link audio from folder</p>
                <p style={{ fontSize:12,color:C2.muted,marginBottom:12,lineHeight:1.6 }}>
                  After importing (or on a new device), point to your audio folder from Google Drive.
                  Files are matched by <strong style={{color:C2.text}}>filename</strong> — folder structure doesn't matter.
                </p>
                <label style={actionBtn("#f59e0b")}>
                  📁 Choose audio folder to re-link
                  <input ref={relinkFileRef} type="file" accept="audio/*" multiple webkitdirectory="true" style={{display:"none"}} onChange={handleRelink}/>
                </label>

                {relinkStatus&&(
                  <div style={{ marginTop:10,padding:"12px 14px",borderRadius:9,background:`${relinkStatus.linked===relinkStatus.total?"#22c55e":"#f59e0b"}18`,border:`1px solid ${relinkStatus.linked===relinkStatus.total?"#22c55e":"#f59e0b"}44`,fontSize:12,color:C2.text,lineHeight:1.7 }}>
                    <div style={{fontWeight:700,marginBottom:4}}>
                      {relinkStatus.linked === relinkStatus.total
                        ? `✅ All ${relinkStatus.total} clips re-linked successfully! Reload the page to apply.`
                        : `⚠️ ${relinkStatus.linked} / ${relinkStatus.total} clips re-linked.`}
                    </div>
                    {relinkStatus.missing.length>0&&(
                      <>
                        <div style={{color:C2.muted,marginBottom:4}}>Could not find these files — check filenames match exactly:</div>
                        <div style={{fontFamily:"monospace",fontSize:11,color:"#f59e0b",lineHeight:2}}>
                          {relinkStatus.missing.map(n=><div key={n}>• {n}</div>)}
                        </div>
                      </>
                    )}
                    {relinkStatus.linked===relinkStatus.total&&(
                      <button onClick={()=>window.location.reload()} style={{marginTop:8,padding:"6px 14px",borderRadius:8,background:"#22c55e",border:"none",color:"#fff",fontWeight:700,fontSize:12,cursor:"pointer"}}>
                        Reload now
                      </button>
                    )}
                  </div>
                )}

                <hr style={{ border:"none",borderTop:`1px solid ${C2.border}`,margin:"20px 0" }}/>

                <p style={{ fontSize:11,fontWeight:700,color:C2.muted,textTransform:"uppercase",letterSpacing:.8,marginBottom:4 }}>Audio Manifest</p>
                <p style={{ fontSize:12,color:C2.muted,marginBottom:10,lineHeight:1.6 }}>
                  The manifest tells the app which audio files are bundled. Currently bundled themes:
                </p>
                <div style={{ background:C2.card,borderRadius:10,padding:"10px 14px",border:`1px solid ${C2.border}`,marginBottom:14 }}>
                  {Object.keys(ASSET_THEMES).length === 0
                    ? <p style={{fontSize:12,color:C2.muted,fontStyle:"italic"}}>No bundled themes — run generateManifest.js and redeploy.</p>
                    : Object.entries(ASSET_THEMES).map(([name,files])=>(
                        <div key={name} style={{display:"flex",justifyContent:"space-between",padding:"4px 0",borderBottom:`1px solid ${C2.border}`}}>
                          <span style={{fontSize:12,color:C2.text,fontWeight:600}}>{name}</span>
                          <span style={{fontSize:11,color:C2.muted}}>{files.length} file{files.length!==1?"s":""}</span>
                        </div>
                      ))
                  }
                </div>
                <button onClick={downloadGeneratedManifest} style={actionBtn("#8b5cf6")}>
                  ⚙ Generate &amp; download audioManifest.js
                </button>
                <p style={{ fontSize:11,color:C2.muted,marginTop:8,lineHeight:1.5 }}>
                  Downloads a ready-to-use <code style={{color:C2.accent}}>audioManifest.js</code>. Replace <code style={{color:C2.accent}}>src/audioManifest.js</code> in your repo and redeploy to apply.<br/>
                  <strong style={{color:C2.text}}>To add brand new audio files:</strong> add them to <code style={{color:C2.accent}}>src/assests/</code> and run <code style={{color:C2.accent}}>node generateManifest.js</code> locally instead — that script generates the webpack import statements the app needs.
                </p>
              </>}

            </div>

            <div style={{ display:"flex",gap:8,padding:"14px 20px",borderTop:`1px solid ${C2.border}` }}>
              <button onClick={()=>setOpen(false)} style={{ padding:"10px 16px",borderRadius:9,background:"transparent",border:`1px solid ${C2.border}`,color:C2.muted,cursor:"pointer",fontSize:13 }}>Cancel</button>
              <button onClick={applyAll} style={{ flex:1,padding:"10px",borderRadius:9,background:"#7c6af7",border:"none",color:"#fff",fontWeight:700,fontSize:13,cursor:"pointer" }}>Apply</button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}


