/**
 * audioManifest.js — AUTO-GENERATED by generateManifest.js
 * Do not edit manually. Run: node generateManifest.js
 */

/* eslint-disable */

import asset_0 from "./assests/acAssets/Furniture_NH_Inv_Icon.png";
import asset_1 from "./assests/acAssets/Main_Theme_PG.mp3";
import asset_2 from "./assests/acAssets/WW_Title.flac";
import asset_3 from "./assests/acAssets/acnl_-_exclamation.mp3";
import asset_4 from "./assests/acAssets/amazed-emote-animal-crossing.mp3";
import asset_5 from "./assests/acAssets/animal-crossing-catch-sound.mp3";
import asset_6 from "./assests/acAssets/animal-crossing-new-horizons-theme-music-101soundboards.mp3";
import asset_7 from "./assests/acAssets/animal-crossing-sound-effect-101soundboards.mp3";
import asset_8 from "./assests/acAssets/curiosity-emote-animal-crossing.mp3";
import asset_9 from "./assests/acAssets/glee-emote-animal-crossing.mp3";
import asset_10 from "./assests/acAssets/greetings-emote-animal-crossing.mp3";
import asset_11 from "./assests/acAssets/inspiration-emote-animal-crossing.mp3";
import asset_12 from "./assests/acAssets/pride-emote-animal-crossing.mp3";
import asset_13 from "./assests/acAssets/surprise-emote-animal-crossing.mp3";
import asset_14 from "./assests/haloAssets/1600px-Halo_logo_(2010-present).png";
import asset_15 from "./assests/haloAssets/26-halo.mp3";
import asset_16 from "./assests/haloAssets/Halo Icon 2.png";
import asset_17 from "./assests/haloAssets/Halo Icon.jpg";
import asset_18 from "./assests/haloAssets/five_mins_remaining.mp3";
import asset_19 from "./assests/haloAssets/grunt-birthday-party.mp3";
import asset_20 from "./assests/haloAssets/halo-reach-30-seconds-remain.mp3";
import asset_21 from "./assests/haloAssets/halo-theme-song-original-2m252s.mp3";
import asset_22 from "./assests/haloAssets/halo_3_piano_chord.mp3";
import asset_23 from "./assests/haloAssets/warthog-run.mp3";
import asset_24 from "./assests/lolAssets/Announcer_Female1_006.ogg";
import asset_25 from "./assests/lolAssets/Announcer_Female1_032.ogg";
import asset_26 from "./assests/lolAssets/Announcer_Female1_036.ogg";
import asset_27 from "./assests/lolAssets/Announcer_Female1_060.ogg";
import asset_28 from "./assests/lolAssets/Announcer_Female1_064.ogg";
import asset_29 from "./assests/lolAssets/Announcer_Female1_070.ogg";
import asset_30 from "./assests/lolAssets/Announcer_Female1_073.ogg";
import asset_31 from "./assests/lolAssets/Announcer_Female1_078.ogg";
import asset_32 from "./assests/lolAssets/Announcer_Female1_084.ogg";
import asset_33 from "./assests/lolAssets/Announcer_Female1_096.ogg";
import asset_34 from "./assests/lolAssets/Announcer_Female1_104.ogg";
import asset_35 from "./assests/lolAssets/Announcer_Female1_117.ogg";
import asset_36 from "./assests/lolAssets/Announcer_Female1_126.ogg";
import asset_37 from "./assests/lolAssets/League_of_Legends_Icon.png";
import asset_38 from "./assests/lolAssets/atreus-1.mp3";
import asset_39 from "./assests/lolAssets/doublekill.ogg";
import asset_40 from "./assests/lolAssets/firstblood.mp3";
import asset_41 from "./assests/lolAssets/jinx_IreAe7l.mp3";
import asset_42 from "./assests/lolAssets/mastery_emote_tier5.mp3";
import asset_43 from "./assests/lolAssets/matchmakingqueued_1.mp3";
import asset_44 from "./assests/lolAssets/pentakill.mp3";
import asset_45 from "./assests/lolAssets/ping_missing.mp3";
import asset_46 from "./assests/nintendoAssets/Nintendo Icon.png";
import asset_47 from "./assests/nintendoAssets/download-hd-nintendo-red-logo-png-701751694774116r0chk91ghq.png";
import asset_48 from "./assests/nintendoAssets/mario-kart-double-dash-opening-hdo.mp3";
import asset_49 from "./assests/nintendoAssets/mario-kart-wii-item-box.mp3";
import asset_50 from "./assests/nintendoAssets/mario-kart-wii-music-final-lap.mp3";
import asset_51 from "./assests/nintendoAssets/mario-meme.mp3";
import asset_52 from "./assests/nintendoAssets/mii-victoy-theme.mp3";
import asset_53 from "./assests/nintendoAssets/mk64_firstplace-1.mp3";
import asset_54 from "./assests/nintendoAssets/mk64_racestart.mp3";
import asset_55 from "./assests/nintendoAssets/smash-bros-light-of-hope-eurobeat-edition.mp3";
import asset_56 from "./assests/nintendoAssets/super-mario-bros_2.mp3";
import asset_57 from "./assests/nintendoAssets/super-mario-bros_DhUAiGM.mp3";
import asset_58 from "./assests/nintendoAssets/super-mario-death-sound-sound-effect.mp3";
import asset_59 from "./assests/nintendoAssets/super_smash_bros_brawl_theme.mp3";
import asset_60 from "./assests/nintendoAssets/title-bgm.mp3";
import asset_61 from "./assests/nintendoAssets/untitled_3.mp3";
import asset_62 from "./assests/pikminAssets/PikminLogo.png";
import asset_63 from "./assests/pikminAssets/onion-discovery-pikmin-1.mp3";
import asset_64 from "./assests/pikminAssets/onion-discovery-pikmin-4.mp3";
import asset_65 from "./assests/pikminAssets/pikmin-1-ship-upgraded.mp3";
import asset_66 from "./assests/pikminAssets/pikmin-3-mission-complete.mp3";
import asset_67 from "./assests/pikminAssets/pikmin-4-ship-upgraded.mp3";
import asset_68 from "./assests/pikminAssets/pikmin-boss-die.mp3";
import asset_69 from "./assests/pikminAssets/pikmin-boss-reveal.mp3";
import asset_70 from "./assests/pikminAssets/pikmin-discovery-pikmin-2.mp3";
import asset_71 from "./assests/pikminAssets/pikmin-discovery-pikmin-3.mp3";
import asset_72 from "./assests/pikminAssets/pikmin-extinction.mp3";
import asset_73 from "./assests/pikminAssets/pikmin-gcn.mp3";
import asset_74 from "./assests/pikminAssets/pikmin.gif";
import asset_75 from "./assests/pikminAssets/whistle_RjClohy.mp3";
import asset_76 from "./assests/pokemonAssets/06-caught-a-pokemon.mp3";
import asset_77 from "./assests/pokemonAssets/111-pokemon-recovery.mp3";
import asset_78 from "./assests/pokemonAssets/129-received-an-item.mp3";
import asset_79 from "./assests/pokemonAssets/12_3.mp3";
import asset_80 from "./assests/pokemonAssets/old-pokemon-battle-music.mp3";
import asset_81 from "./assests/pokemonAssets/pokemon-battle.mp3";
import asset_82 from "./assests/pokemonAssets/pokemon-evolve.mp3";
import asset_83 from "./assests/pokemonAssets/pokemon-red-blue-music-wild-pokemon-victory-theme-1.mp3";
import asset_84 from "./assests/pokemonAssets/pokemon-red_blue_yellow-item-found-sound-effect.mp3";
import asset_85 from "./assests/pokemonAssets/pokemon-red_blue_yellow-level-up-sound-effect.mp3";
import asset_86 from "./assests/pokemonAssets/tumblr_m9a6eqNYze1qfqgb9o1_500.webp";
import asset_87 from "./assests/squidGameAssets/Squid Game Logo.png";
import asset_88 from "./assests/squidGameAssets/Way Forward.mp3";
import asset_89 from "./assests/starcraftAssets/Starcraft 2 Icon.png";
import asset_90 from "./assests/valorantAssets/Champions_2025_Kill_Banner.webp";
import asset_91 from "./assests/valorantAssets/Reaver_Kill_Banner_White.webp";
import asset_92 from "./assests/valorantAssets/hd-valorant-official-symbol-sign-logo-png-701751694788082d3btqfskcj.png";

export const ASSET_THEMES = {
  "acAssets": [
    { name: "Furniture_NH_Inv_Icon.png", url: asset_0 },
    { name: "Main_Theme_PG.mp3", url: asset_1 },
    { name: "WW_Title.flac", url: asset_2 },
    { name: "acnl_-_exclamation.mp3", url: asset_3 },
    { name: "amazed-emote-animal-crossing.mp3", url: asset_4 },
    { name: "animal-crossing-catch-sound.mp3", url: asset_5 },
    { name: "animal-crossing-new-horizons-theme-music-101soundboards.mp3", url: asset_6 },
    { name: "animal-crossing-sound-effect-101soundboards.mp3", url: asset_7 },
    { name: "curiosity-emote-animal-crossing.mp3", url: asset_8 },
    { name: "glee-emote-animal-crossing.mp3", url: asset_9 },
    { name: "greetings-emote-animal-crossing.mp3", url: asset_10 },
    { name: "inspiration-emote-animal-crossing.mp3", url: asset_11 },
    { name: "pride-emote-animal-crossing.mp3", url: asset_12 },
    { name: "surprise-emote-animal-crossing.mp3", url: asset_13 },
  ],
  "haloAssets": [
    { name: "1600px-Halo_logo_(2010-present).png", url: asset_14 },
    { name: "26-halo.mp3", url: asset_15 },
    { name: "Halo Icon 2.png", url: asset_16 },
    { name: "Halo Icon.jpg", url: asset_17 },
    { name: "five_mins_remaining.mp3", url: asset_18 },
    { name: "grunt-birthday-party.mp3", url: asset_19 },
    { name: "halo-reach-30-seconds-remain.mp3", url: asset_20 },
    { name: "halo-theme-song-original-2m252s.mp3", url: asset_21 },
    { name: "halo_3_piano_chord.mp3", url: asset_22 },
    { name: "warthog-run.mp3", url: asset_23 },
  ],
  "lolAssets": [
    { name: "Announcer_Female1_006.ogg", url: asset_24 },
    { name: "Announcer_Female1_032.ogg", url: asset_25 },
    { name: "Announcer_Female1_036.ogg", url: asset_26 },
    { name: "Announcer_Female1_060.ogg", url: asset_27 },
    { name: "Announcer_Female1_064.ogg", url: asset_28 },
    { name: "Announcer_Female1_070.ogg", url: asset_29 },
    { name: "Announcer_Female1_073.ogg", url: asset_30 },
    { name: "Announcer_Female1_078.ogg", url: asset_31 },
    { name: "Announcer_Female1_084.ogg", url: asset_32 },
    { name: "Announcer_Female1_096.ogg", url: asset_33 },
    { name: "Announcer_Female1_104.ogg", url: asset_34 },
    { name: "Announcer_Female1_117.ogg", url: asset_35 },
    { name: "Announcer_Female1_126.ogg", url: asset_36 },
    { name: "League_of_Legends_Icon.png", url: asset_37 },
    { name: "atreus-1.mp3", url: asset_38 },
    { name: "doublekill.ogg", url: asset_39 },
    { name: "firstblood.mp3", url: asset_40 },
    { name: "jinx_IreAe7l.mp3", url: asset_41 },
    { name: "mastery_emote_tier5.mp3", url: asset_42 },
    { name: "matchmakingqueued_1.mp3", url: asset_43 },
    { name: "pentakill.mp3", url: asset_44 },
    { name: "ping_missing.mp3", url: asset_45 },
  ],
  "nintendoAssets": [
    { name: "Nintendo Icon.png", url: asset_46 },
    { name: "download-hd-nintendo-red-logo-png-701751694774116r0chk91ghq.png", url: asset_47 },
    { name: "mario-kart-double-dash-opening-hdo.mp3", url: asset_48 },
    { name: "mario-kart-wii-item-box.mp3", url: asset_49 },
    { name: "mario-kart-wii-music-final-lap.mp3", url: asset_50 },
    { name: "mario-meme.mp3", url: asset_51 },
    { name: "mii-victoy-theme.mp3", url: asset_52 },
    { name: "mk64_firstplace-1.mp3", url: asset_53 },
    { name: "mk64_racestart.mp3", url: asset_54 },
    { name: "smash-bros-light-of-hope-eurobeat-edition.mp3", url: asset_55 },
    { name: "super-mario-bros_2.mp3", url: asset_56 },
    { name: "super-mario-bros_DhUAiGM.mp3", url: asset_57 },
    { name: "super-mario-death-sound-sound-effect.mp3", url: asset_58 },
    { name: "super_smash_bros_brawl_theme.mp3", url: asset_59 },
    { name: "title-bgm.mp3", url: asset_60 },
    { name: "untitled_3.mp3", url: asset_61 },
  ],
  "pikminAssets": [
    { name: "PikminLogo.png", url: asset_62 },
    { name: "onion-discovery-pikmin-1.mp3", url: asset_63 },
    { name: "onion-discovery-pikmin-4.mp3", url: asset_64 },
    { name: "pikmin-1-ship-upgraded.mp3", url: asset_65 },
    { name: "pikmin-3-mission-complete.mp3", url: asset_66 },
    { name: "pikmin-4-ship-upgraded.mp3", url: asset_67 },
    { name: "pikmin-boss-die.mp3", url: asset_68 },
    { name: "pikmin-boss-reveal.mp3", url: asset_69 },
    { name: "pikmin-discovery-pikmin-2.mp3", url: asset_70 },
    { name: "pikmin-discovery-pikmin-3.mp3", url: asset_71 },
    { name: "pikmin-extinction.mp3", url: asset_72 },
    { name: "pikmin-gcn.mp3", url: asset_73 },
    { name: "pikmin.gif", url: asset_74 },
    { name: "whistle_RjClohy.mp3", url: asset_75 },
  ],
  "pokemonAssets": [
    { name: "06-caught-a-pokemon.mp3", url: asset_76 },
    { name: "111-pokemon-recovery.mp3", url: asset_77 },
    { name: "129-received-an-item.mp3", url: asset_78 },
    { name: "12_3.mp3", url: asset_79 },
    { name: "old-pokemon-battle-music.mp3", url: asset_80 },
    { name: "pokemon-battle.mp3", url: asset_81 },
    { name: "pokemon-evolve.mp3", url: asset_82 },
    { name: "pokemon-red-blue-music-wild-pokemon-victory-theme-1.mp3", url: asset_83 },
    { name: "pokemon-red_blue_yellow-item-found-sound-effect.mp3", url: asset_84 },
    { name: "pokemon-red_blue_yellow-level-up-sound-effect.mp3", url: asset_85 },
    { name: "tumblr_m9a6eqNYze1qfqgb9o1_500.webp", url: asset_86 },
  ],
  "squidGameAssets": [
    { name: "Squid Game Logo.png", url: asset_87 },
    { name: "Way Forward.mp3", url: asset_88 },
  ],
  "starcraftAssets": [
    { name: "Starcraft 2 Icon.png", url: asset_89 },
  ],
  "valorantAssets": [
    { name: "Champions_2025_Kill_Banner.webp", url: asset_90 },
    { name: "Reaver_Kill_Banner_White.webp", url: asset_91 },
    { name: "hd-valorant-official-symbol-sign-logo-png-701751694788082d3btqfskcj.png", url: asset_92 },
  ]
};

export function getManifestFileMap(themeName) {
  const files = ASSET_THEMES[themeName] || [];
  const map = {};
  files.forEach(f => { map[f.name] = f.url; });
  return map;
}

export function getManifestFiles(themeName) {
  return ASSET_THEMES[themeName] || [];
}

export function getManifestThemeNames() {
  return Object.keys(ASSET_THEMES);
}
