/**
 * audioManifest.js — generated by the app on 2026-03-22T04:23:38.975Z
 *
 * NOTE: This file contains the STRUCTURE only — not the actual import statements.
 * To add NEW audio files, run: node generateManifest.js from your project root.
 * That script scans src/assests/ and rebuilds this file with correct imports.
 */

/* eslint-disable */

// ── Re-run 'node generateManifest.js' to regenerate with new files ──
// The imports below need to be resolved at build time by webpack.
// This exported structure shows what the current build contains.

export const ASSET_THEMES = {
};

export function getManifestFileMap(themeName) {
  const files = ASSET_THEMES[themeName] || [];
  const map = {};
  files.forEach(f => { map[f.name] = f.url; });
  return map;
}

export function getManifestFiles(themeName) {
  return ASSET_THEMES[themeName] || [];
}

export function getManifestThemeNames() {
  return Object.keys(ASSET_THEMES);
}
